version: '3'

services:
  web:
    build: .
    environment:
      FLASK_ENV: development
      SERVER_NAME: bcb.manager.com:5000
      OAUTHLIB_INSECURE_TRANSPORT: 1
    volumes:
      - .:/code
    ports:
      - "5000:5000"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
  huey:
    # Huey needs the same code and packages as the web container (because it runs a lot of the code through import statements)
    build: .
    volumes:
      - .:/code
        # Not sure what this is exactly but nothing works without it
      - /dev/shm:/dev/shm
    command: huey_consumer app.huey
    depends_on: 
      - redis
  sass:
    image: danmaq/ruby-sass
    volumes:
      - .:/code
    # Watch for changes to the sass folder and recompile sass on any changes
    command: sass --style compressed --watch /code/app/sass/main.scss:/code/app/static/styles/main.css
